---
title: "Coding2 - Assignment 3"
author: "Ghazal"
output:
  prettydoc::html_pretty:
    theme: hpstr
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

#Cleaning the environment 
rm(list = ls())

# Loading packages
library(rvest)
library(xml2)
library(data.table)
library(kableExtra)
library(httr)
library(polite)
library(purrr)

```


```{r eval=FALSE, include=FALSE}

# Identifying the link
perfumes_url <- read_html("https://www.overstock.com/")

relative_link <- perfumes_url %>% html_node('.td') %>% html_attr('href') 









# Creating relative links
relative_link <- perfumes_url %>% html_nodes('.title a') %>% html_attr('href') 

# Create links of the website
links <- paste0('', relative_link)

# Creating elements
t_titles <- perfumes_url %>% html_nodes('.title') %>% html_text()
Titles <- gsub("[\n.]","", t_titles)

a_author <- perfumes_url %>% html_nodes('.author') %>% html_text()
Author <- gsub("[\n.]","", a_author)

Date_Pubished <- perfumes_url %>% html_nodes('.published') %>% html_text()

Format <- perfumes_url %>% html_nodes('.format') %>% html_text()

# Create Data frame and put everything together 
df <- data.frame('Titles' = Titles, 'Author' = Author, 'Date_Pubished' = Date_Pubished, 'Format' = Format, 'links' = links)


```


```{r}

# Creating Function 

scrape_data <- function(t_url) {

perfumes_url <- read_html(t_url)

# Creating relative links
relative_link <- perfumes_url %>% html_nodes('.title a') %>% html_attr('href') 

# Create links of the website
links <- paste0('https://www.perfumedepository.com', relative_link)


# Creating elements
t_titles <- perfumes_url %>% html_nodes('.title') %>% html_text()
Titles <- gsub("[\n.]","", t_titles)

a_author <- perfumes_url %>% html_nodes('.author') %>% html_text()
Author <- gsub("[\n.]","", a_author)


Date_Pubished <- perfumes_url %>% html_nodes('.published') %>% html_text()

Format <- perfumes_url %>% html_nodes('.format') %>% html_text()



# Create Data frame and put everything together 
df <- data.frame('Titles' = Titles, 'Author' = Author, 
                 'Date_Pubished' = Date_Pubished, 
                 'Format' = Format, 'links' = links)

return(df)
}


```


```{r, echo=TRUE, results='hide'}

# Calling the function
scrape_data("https://www.perfumedepository.com/bestsellers")

# Selecting multiple pages
links <- paste0('https://www.perfumedepository.com/bestsellers?page=', 1:3)

# Apply the function
list_of_dfs <- lapply(links, scrape_data)
final_df <- rbindlist(list_of_dfs)


```


```{r}

head(final_df)

```

```{r}


library(jsonlite)
require(httr)

headers = c(
  `sec-ch-ua` = '" Not A;Brand";v="99", "Chromium";v="96", "Google Chrome";v="96"',
  `Referer` = 'https://www.overstock.com/',
  `sec-ch-ua-mobile` = '?0',
  `User-Agent` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36',
  `sec-ch-ua-platform` = '"macOS"'
)

params = list(
  `version` = '1.3.0'
)

res <- httr::GET(url = 'https://seoab.io/s/69c70e8b-119f-4d73-9270-e099922a983e/www.overstock.com/Health-Beauty/Womens-Fragrances/21088/subcat.html/0.json', httr::add_headers(.headers=headers), query = params)

#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
# res <- httr::GET(url = 'https://seoab.io/s/69c70e8b-119f-4d73-9270-e099922a983e/www.overstock.com/Health-Beauty/Womens-Fragrances/21088/subcat.html/0.json?version=1.3.0', httr::add_headers(.headers=headers))

```

```{r}

res$request

res$times


```

